// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBA.Data;

namespace NBA.Migrations
{
    [DbContext(typeof(MvcWebAppDbContext))]
    [Migration("20200722160343_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("NBA.Models.Player", b =>
                {
                    b.Property<int>("playerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("playerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("playerNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("teamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("playerId");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
